version: '3'

tasks:
  run:
    cmds:
      - pnpm dev

  build:
    cmds:
      - docker build -t namhq1989/tapnchill-website:latest -t namhq1989/tapnchill-website:$(git rev-parse --short HEAD) .
      - docker push namhq1989/tapnchill-website:latest
      - docker push namhq1989/tapnchill-website:$(git rev-parse --short HEAD)
