import {
  Bird,
  Bug,
  CloudRain,
  Coffee,
  Droplet,
  FlameKindling,
  Gauge,
  TrainTrack,
  Waves,
  Wind,
  Zap,
} from 'lucide-react'
import { IEffect } from '@/effect/types.ts'

const listEffects: IEffect[] = [
  {
    id: 'crackling-fire',
    name: 'Crackling fire',
    icon: FlameKindling,
    file: 'crackling-fire.mp3',
    isAdded: false,
    volume: 100,
    mutedVolume: 0,
  },
  {
    id: 'rain',
    name: 'Rain',
    icon: CloudRain,
    file: 'rain.mp3',
    isAdded: false,
    volume: 100,
    mutedVolume: 0,
  },
  {
    id: 'wind',
    name: 'Wind',
    icon: Wind,
    file: 'wind-noise.mp3',
    isAdded: false,
    volume: 100,
    mutedVolume: 0,
  },
  {
    id: 'water',
    name: 'Water',
    icon: Droplet,
    file: 'water.mp3',
    isAdded: false,
    volume: 100,
    mutedVolume: 0,
  },
  {
    id: 'sea',
    name: 'Sea',
    icon: Waves,
    file: 'sea.mp3',
    isAdded: false,
    volume: 100,
    mutedVolume: 0,
  },
  {
    id: 'train',
    name: 'Train',
    icon: TrainTrack,
    file: 'train.mp3',
    isAdded: false,
    volume: 100,
    mutedVolume: 0,
  },
  {
    id: 'bird',
    name: 'Bird',
    icon: Bird,
    file: 'bird.mp3',
    isAdded: false,
    volume: 100,
    mutedVolume: 0,
  },
  {
    id: 'coffee-shop',
    name: 'Coffee shop',
    icon: Coffee,
    file: 'coffee-shop.mp3',
    isAdded: false,
    volume: 100,
    mutedVolume: 0,
  },
  {
    id: 'thunder',
    name: 'Thunder',
    icon: Zap,
    file: 'thunder.mp3',
    isAdded: false,
    volume: 100,
    mutedVolume: 0,
  },
  {
    id: 'cricket',
    name: 'Cricket',
    icon: Bug,
    file: 'cricket.mp3',
    isAdded: false,
    volume: 100,
    mutedVolume: 0,
  },
  {
    id: 'driving',
    name: 'Driving',
    icon: Gauge,
    file: 'driving.mp3',
    isAdded: false,
    volume: 100,
    mutedVolume: 0,
  },
]

export default listEffects
